# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  # config.vm.box = "fedora/35-cloud-base"
  # config.vm.box = "rockylinux/8"
  config.vm.box = "generic/ubuntu2004"

  # rockylinux/8 root is only 5 GB
  if config.vm.box == "rockylinux/8"
    # Requires VAGRANT_EXPERIMENTAL=disks
    # https://www.vagrantup.com/docs/disks/usage
    config.vm.disk :disk, size: "10GB", primary: true
  end

  config.vm.provider "virtualbox" do |vb|
    vb.cpus = 2
    vb.memory = 4096
  end

  config.vm.provider "libvirt" do |lv|
    lv.cpus = 2
    lv.memory = 4096
  end

  config.vm.synced_folder './', '/vagrant', type: 'rsync'

  config.vm.provision "shell", path: "prerequisites.sh", privileged: false
end
