# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "fedora/35-cloud-base"

  config.vm.provider "virtualbox" do |vb|
    vb.cpus = 2
    vb.memory = 4096
  end

  config.vm.provider "libvirt" do |lv|
    lv.cpus = 2
    lv.memory = 4096
  end

  config.vm.synced_folder './', '/vagrant', type: 'rsync'

  config.vm.provision "shell", path: "setup.sh", privileged: true

end
